import sys
import os
import json
import atexit
import logging
import webbrowser
import winreg
import tempfile
import subprocess
from datetime import datetime
from functools import lru_cache
from logging.handlers import RotatingFileHandler
from typing import Optional, Tuple
from urllib.parse import urlparse
from PyQt6.QtSvg import QSvgRenderer
from PyQt6.QtWidgets import (QApplication, QWidget, QMenu, QFileDialog, QSystemTrayIcon,
                             QHBoxLayout, QVBoxLayout, QPushButton, QDialog, QFormLayout,
                             QLineEdit, QComboBox, QSpinBox, QCheckBox, QLabel, QGroupBox,
                             QScrollArea, QMessageBox)
from PyQt6.QtGui import (QPainter, QColor, QPen, QPixmap, QCursor, QIcon, QFont,
                         QPainterPath, QFontMetrics, QDrag)
from PyQt6.QtCore import (Qt, QRect, QPoint, pyqtSignal, QObject, QTimer, QSettings,
                           QSize, QEvent, QMimeData, QUrl)
import keyboard

from theme import (ThemeManager, panel_qss, cancel_btn_qss, feedback_qss,
                   conflict_qss)

# Centralised temp-file management to avoid leaks in %TEMP%.
# All temp files generated by "Abrir con..." and the Auto action are created
# inside this directory, which is purged at startup (cleans leftovers from
# previous sessions after an abrupt exit) and at exit.
CAPTURA_TEMP_DIR = os.path.join(tempfile.gettempdir(), 'kdgdkd_captura')


def _cleanup_captura_temp_dir():
    if not os.path.isdir(CAPTURA_TEMP_DIR):
        return
    try:
        for name in os.listdir(CAPTURA_TEMP_DIR):
            try:
                os.remove(os.path.join(CAPTURA_TEMP_DIR, name))
            except OSError:
                # The external viewer may still have the file open; ignore
                # it and retry on the next run.
                pass
    except OSError:
        pass


def new_temp_image_path(suffix=".png"):
    os.makedirs(CAPTURA_TEMP_DIR, exist_ok=True)
    fd, path = tempfile.mkstemp(suffix=suffix, dir=CAPTURA_TEMP_DIR)
    os.close(fd)
    return path


_cleanup_captura_temp_dir()
atexit.register(_cleanup_captura_temp_dir)

SETTINGS_ORG = "kdgdkd"
SETTINGS_APP = "Captura"


class Translator:
    _instance = None

    def __init__(self):
        self._strings = {}
        self._locale = "es"

    @classmethod
    def instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def t(self, key: str, **kwargs) -> str:
        text = self._strings.get(key, key)
        if kwargs:
            return text.format(**kwargs)
        return text

    def load_locale(self, locale: str):
        base_dir = os.path.dirname(os.path.abspath(__file__))
        locale_file = os.path.join(base_dir, 'locales', f'{locale}.json')
        try:
            with open(locale_file, 'r', encoding='utf-8') as f:
                self._strings = json.load(f)
            self._locale = locale
        except (FileNotFoundError, json.JSONDecodeError):
            if locale != 'es':
                self.load_locale('es')

    @property
    def locale(self) -> str:
        return self._locale


def tr(key: str, **kwargs) -> str:
    return Translator.instance().t(key, **kwargs)


def _setup_logging():
    log_dir = os.path.join(os.environ.get('LOCALAPPDATA', tempfile.gettempdir()), 'Captura')
    os.makedirs(log_dir, exist_ok=True)
    log_path = os.path.join(log_dir, 'captura.log')
    handler = RotatingFileHandler(log_path, maxBytes=1_000_000, backupCount=2, encoding='utf-8')
    handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s %(message)s'))
    logging.basicConfig(level=logging.WARNING, handlers=[handler])

    def _excepthook(exc_type, exc_val, exc_tb):
        logging.critical("Excepción no manejada", exc_info=(exc_type, exc_val, exc_tb))
        sys.__excepthook__(exc_type, exc_val, exc_tb)

    sys.excepthook = _excepthook


_setup_logging()

# SVG icons for the capture bar buttons
ICON_AUTO = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><path d="M128,189.09l54.72,33.65a8.4,8.4,0,0,0,12.52-9.17l-14.88-62.79,48.7-42A8.46,8.46,0,0,0,224.27,94L160.36,88.8,135.74,29.2a8.36,8.36,0,0,0-15.48,0L95.64,88.8,31.73,94a8.46,8.46,0,0,0-4.79,14.83l48.7,42L60.76,213.57a8.4,8.4,0,0,0,12.52,9.17Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/></svg>'''

ICON_COPY = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><rect x="40" y="72" width="144" height="144" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><polyline points="72 40 216 40 216 184" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/></svg>'''

ICON_SAVE = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><line x1="128" y1="144" x2="128" y2="32" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><polyline points="216 144 216 208 40 208 40 144" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><polyline points="168 104 128 144 88 104" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/></svg>'''

ICON_OPEN = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><path d="M92.69,216H48a8,8,0,0,1-8-8V163.31a8,8,0,0,1,2.34-5.65L165.66,34.34a8,8,0,0,1,11.31,0L221.66,79a8,8,0,0,1,0,11.31L98.34,213.66A8,8,0,0,1,92.69,216Z" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><line x1="136" y1="64" x2="192" y2="120" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><line x1="164" y1="92" x2="68" y2="188" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><line x1="95.49" y1="215.49" x2="40.51" y2="160.51" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/></svg>'''

ICON_CANCEL = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256"><rect width="256" height="256" fill="none"/><line x1="200" y1="56" x2="56" y2="200" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/><line x1="200" y1="200" x2="56" y2="56" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="20"/></svg>'''

STANDARD_RATIOS = [
    (1, 1),   # Square
    (4, 3),   # Traditional
    (3, 2),   # Photography
    (16, 9),  # Widescreen
    (16, 10), # Monitors
    (21, 9),  # Ultrawide
    (9, 16),  # Vertical
    (3, 1),   # Panoramic
    (1, 3),   # Vertical extreme
    (5, 4),   # Old format
    (3, 4),   # Vertical traditional
    (2, 3),   # Vertical photography
]


@lru_cache(maxsize=128)
def _compute_ratio_info(w: int, h: int) -> Optional[Tuple[str, str]]:
    if w == 0 or h == 0:
        return None

    is_vertical = h > w
    if is_vertical:
        w, h = h, w

    current_ratio = w / h

    best_match = None
    best_diff = float('inf')

    for std_w, std_h in STANDARD_RATIOS:
        if std_h > std_w:
            cmp_w, cmp_h = std_h, std_w
        else:
            cmp_w, cmp_h = std_w, std_h

        standard_ratio = cmp_w / cmp_h
        diff = abs(current_ratio - standard_ratio) / standard_ratio

        if diff < best_diff:
            best_diff = diff
            tight_margin = 3 / max(w, h)
            wide_margin = 0.15

            if diff <= tight_margin:
                sign = ''
            elif diff <= wide_margin:
                sign = '+' if current_ratio > standard_ratio else '-'
            else:
                continue

            if is_vertical:
                best_match = (f"{std_h}:{std_w}", sign)
            else:
                best_match = (f"{std_w}:{std_h}", sign)

    return best_match

class HotkeyRecorder(QWidget):
    key_signal = pyqtSignal(str)
    active_recorder = None

    def __init__(self, initial_value, parent=None):
        super().__init__(parent)
        self.is_recording = False
        self.hook_id = None
        self.recorded_keys = []
        
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        self.line_edit = QLineEdit(initial_value)
        self.line_edit.setReadOnly(True)
        self.btn = QPushButton(tr("settings.btn.record"))
        self.btn.setFixedWidth(80)
        self.btn.setFocusPolicy(Qt.FocusPolicy.NoFocus) 
        self.btn.clicked.connect(self.toggle_recording)
        layout.addWidget(self.line_edit)
        layout.addWidget(self.btn)
        
        self.key_signal.connect(self._add_key)

    def toggle_recording(self):
        if not self.is_recording:
            self.start_recording()
        else:
            self.stop_recording()

    def start_recording(self):
        # If another recorder is active, stop it. It may be a Qt widget
        # that was already destroyed (dialog closed in a previous session);
        # in that case just clear the reference to avoid RuntimeError.
        prev = HotkeyRecorder.active_recorder
        if prev is not None and prev is not self:
            try:
                prev.stop_recording()
            except RuntimeError:
                HotkeyRecorder.active_recorder = None

        HotkeyRecorder.active_recorder = self
        self.is_recording = True
        self.btn.setText(tr("settings.btn.recording"))
        self.btn.setStyleSheet(f"background-color: {ThemeManager.instance().palette.recording_btn_bg}; color: {ThemeManager.instance().palette.recording_btn_text}; font-weight: bold;")
        self.line_edit.setText("")
        self.line_edit.setPlaceholderText(tr("settings.placeholder.record"))
        self.recorded_keys = []

        # Desactivar atajos globales para evitar que se disparen mientras grabamos
        keyboard.unhook_all()

        # Start the hook to capture keystrokes
        self.hook_id = keyboard.hook(self._on_key_event)

    def stop_recording(self):
        if not self.is_recording:
            return

        self.is_recording = False
        self.btn.setText(tr("settings.btn.record"))
        self.btn.setStyleSheet("")
        if self.hook_id:
            try:
                keyboard.unhook(self.hook_id)
            except (KeyError, ValueError):
                pass
            self.hook_id = None

        if HotkeyRecorder.active_recorder is self:
            HotkeyRecorder.active_recorder = None

    def _on_key_event(self, event):
        if event.event_type == keyboard.KEY_DOWN:
            # Emit signal to update UI from the main thread
            self.key_signal.emit(event.name)

    def _add_key(self, key_name):
        # Avoid capturing key events that activate the button when
        # using keyboard to press "Listo"
        if key_name in ("space", "enter") and not self.recorded_keys:
            return
            
        if key_name not in self.recorded_keys:
            self.recorded_keys.append(key_name)
            self.line_edit.setText("+".join(self.recorded_keys))

    def text(self):
        return self.line_edit.text()

class SettingsDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle(tr("settings.title"))
        self.settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        self.init_ui()

    def closeEvent(self, event):
        # If user closes (Esc/X) while a HotkeyRecorder was recording,
        # stop recording to avoid a static reference to a destroyed Qt widget.
        active = HotkeyRecorder.active_recorder
        if active is not None:
            try:
                active.stop_recording()
            except RuntimeError:
                HotkeyRecorder.active_recorder = None
        super().closeEvent(event)

    def check_modifier_conflicts(self):
        """Check for conflicts between modifier keys and update UI"""
        # Lista de todos los combos de modificadores
        mod_combos = [
            (self.mod_lock, "Bloquear proporción"),
            (self.mod_prop, "Forzar preferidas"),
            (self.mod_inv_prop, "Invertir preferidas")
        ]
        
        
        # Reiniciar todos los combos
        for combo, _ in mod_combos:
            combo.setStyleSheet("")
            combo.setToolTip("")
            # Restaurar todos los items
            for i in range(combo.count()):
                combo.model().item(i).setEnabled(True)
        
        # Verificar conflictos
        used_mods = {}
        for combo, name in mod_combos:
            mod = combo.currentText()
            if mod != "---":
                if mod in used_mods:
                    # Conflicto encontrado
                    conflicted_combo = used_mods[mod]
                    # Marcar ambos combos como conflictivos
                    combo.setStyleSheet(conflict_qss(ThemeManager.instance().palette))
                    combo.setToolTip(f"¡Conflicto! El modificador '{mod}' ya está asignado a '{conflicted_combo}'")
                    
                    conflicted_combo.setStyleSheet(conflict_qss(ThemeManager.instance().palette))
                    conflicted_combo.setToolTip(f"¡Conflicto! El modificador '{mod}' también está asignado a '{name}'")
                else:
                    used_mods[mod] = combo
        
        # Deshabilitar modificadores ya usados en otros combos
        for combo, _ in mod_combos:
            current_mod = combo.currentText()
            for other_combo, _ in mod_combos:
                if other_combo != combo:
                    other_mod = other_combo.currentText()
                    if other_mod != "---" and other_mod != current_mod:
                        # Deshabilitar el modificador usado en el otro combo
                        for i in range(combo.count()):
                            if combo.itemText(i) == other_mod:
                                combo.model().item(i).setEnabled(False)

    def init_ui(self):
        self.resize(480, 550)
        
        # Layout principal de la ventana
        main_layout = QVBoxLayout(self)
        main_layout.setContentsMargins(10, 10, 10, 10)

        # --- ÁREA DE SCROLL ---
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setStyleSheet("QScrollArea { border: none; }")
        
        # Inner container for scroll area
        container = QWidget()
        layout = QVBoxLayout(container)
        layout.setContentsMargins(5, 5, 5, 5)
        layout.setSpacing(8)

        # ==========================================
        # SECTION 1: Shortcuts & Ratios
        # ==========================================
        group_shortcuts = QGroupBox(tr("settings.group.shortcuts"))
        form_shortcuts = QFormLayout(group_shortcuts)
        form_shortcuts.setContentsMargins(10, 15, 10, 10)
        form_shortcuts.setVerticalSpacing(4)

        self.hk_zone = HotkeyRecorder(self.settings.value("hotkey_zone", "print screen"))
        self.hk_full = HotkeyRecorder(self.settings.value("hotkey_full", "shift+print screen"))
        self.hk_silent = HotkeyRecorder(self.settings.value("hotkey_silent", "ctrl+print screen"))
        form_shortcuts.addRow(tr("settings.label.capture_zone"), self.hk_zone)
        form_shortcuts.addRow(tr("settings.label.capture_full"), self.hk_full)
        form_shortcuts.addRow(tr("settings.label.capture_silent"), self.hk_silent)

        self.mod_lock = QComboBox()
        self.mod_lock.addItems([tr("mod.none"), tr("mod.ctrl"), tr("mod.shift"), tr("mod.alt")])
        self.mod_lock.setCurrentText(self.settings.value("mod_lock", "Ctrl"))
        form_shortcuts.addRow(tr("settings.label.lock_ratio"), self.mod_lock)

        self.mod_prop = QComboBox()
        self.mod_prop.addItems([tr("mod.none"), tr("mod.ctrl"), tr("mod.shift"), tr("mod.alt")])
        self.mod_prop.setCurrentText(self.settings.value("mod_prop", "Shift"))
        form_shortcuts.addRow(tr("settings.label.force_ratio"), self.mod_prop)

        self.mod_inv_prop = QComboBox()
        self.mod_inv_prop.addItems([tr("mod.none"), tr("mod.ctrl"), tr("mod.shift"), tr("mod.alt")])
        self.mod_inv_prop.setCurrentText(self.settings.value("mod_inv_prop", "Alt"))
        form_shortcuts.addRow(tr("settings.label.invert_ratio"), self.mod_inv_prop)

        prop_layout = QHBoxLayout()
        self.prop_w = QSpinBox()
        self.prop_w.setRange(1, 9999)
        self.prop_w.setValue(int(self.settings.value("prop_w", 9)))
        self.prop_h = QSpinBox()
        self.prop_h.setRange(1, 9999)
        self.prop_h.setValue(int(self.settings.value("prop_h", 16)))
        prop_layout.addWidget(self.prop_w)
        prop_layout.addWidget(QLabel(":"))
        prop_layout.addWidget(self.prop_h)
        form_shortcuts.addRow(tr("settings.label.pref_ratio"), prop_layout)
        
        # Conectar eventos para detectar conflictos de modificadores
        self.mod_lock.currentTextChanged.connect(self.check_modifier_conflicts)
        self.mod_prop.currentTextChanged.connect(self.check_modifier_conflicts)
        self.mod_inv_prop.currentTextChanged.connect(self.check_modifier_conflicts)
        
        layout.addWidget(group_shortcuts)

        # ==========================================
        # SECTION 2: Magnifier & Coordinates
        # ==========================================
        group_magnifier = QGroupBox(tr("settings.group.magnifier"))
        form_magnifier = QFormLayout(group_magnifier)
        form_magnifier.setContentsMargins(10, 15, 10, 10)
        form_magnifier.setVerticalSpacing(4)

        self.zoom_enabled = QCheckBox()
        self.zoom_enabled.setChecked(self.settings.value("zoom_enabled", True, type=bool))
        form_magnifier.addRow(tr("settings.label.activate_magnifier"), self.zoom_enabled)

        self.default_zoom = QSpinBox()
        self.default_zoom.setRange(1, 20)
        self.default_zoom.setValue(int(self.settings.value("default_zoom", 4)))
        form_magnifier.addRow(tr("settings.label.zoom"), self.default_zoom)

        self.default_mag_size = QSpinBox()
        self.default_mag_size.setRange(60, 400)
        self.default_mag_size.setSingleStep(10)
        self.default_mag_size.setValue(int(self.settings.value("default_mag_size", 120)))
        form_magnifier.addRow(tr("settings.label.mag_size"), self.default_mag_size)

        self.show_coords = QCheckBox()
        self.show_coords.setChecked(self.settings.value("show_coords", True, type=bool))
        form_magnifier.addRow(tr("settings.label.show_coords"), self.show_coords)
        
        layout.addWidget(group_magnifier)

        # ==========================================
        # SECTION 3: Auto
        # ==========================================
        group_auto = QGroupBox(tr("settings.group.auto"))
        form_auto = QFormLayout(group_auto)
        form_auto.setContentsMargins(10, 15, 10, 10)
        form_auto.setVerticalSpacing(4)

        self.auto_action = QComboBox()
        _auto_items = [
            (tr("auto.save"), "Guardar"),
            (tr("auto.open"), "Abrir"),
            (tr("auto.copy"), "Copiar"),
            (tr("auto.none"), "---"),
        ]
        for display_text, data_key in _auto_items:
            self.auto_action.addItem(display_text, data_key)
        saved_action = self.settings.value("auto_action", "Guardar")
        for i in range(self.auto_action.count()):
            if self.auto_action.itemData(i) == saved_action:
                self.auto_action.setCurrentIndex(i)
                break
        form_auto.addRow(tr("settings.label.auto_action"), self.auto_action)

        loc_layout = QHBoxLayout()
        self.save_dir = QLineEdit(self.settings.value("save_dir", os.path.expanduser('~')))
        self.btn_browse = QPushButton("...")
        self.btn_browse.clicked.connect(self.browse_dir)
        loc_layout.addWidget(self.save_dir)
        loc_layout.addWidget(self.btn_browse)
        form_auto.addRow(tr("settings.label.save_dir"), loc_layout)

        editor_layout = QHBoxLayout()
        self.editor_path = QLineEdit(self.settings.value("editor_path", ""))
        self.editor_path.setPlaceholderText(tr("settings.placeholder.editor"))
        self.btn_editor_browse = QPushButton("...")
        self.btn_editor_browse.clicked.connect(self.browse_editor)
        self.btn_paste_url = QPushButton("📋")
        self.btn_paste_url.setFixedWidth(30)
        self.btn_paste_url.setToolTip(tr("settings.tooltip.paste_url"))
        self.btn_paste_url.clicked.connect(self.paste_url)
        editor_layout.addWidget(self.editor_path)
        editor_layout.addWidget(self.btn_paste_url)
        editor_layout.addWidget(self.btn_editor_browse)
        form_auto.addRow(tr("settings.label.open_with"), editor_layout)

        # Auto enable/disable logic
        self.auto_action.currentTextChanged.connect(
            lambda: self.update_auto_state(self.auto_action.currentData()))
        self.update_auto_state(self.auto_action.currentData())

        layout.addWidget(group_auto)

        # ==========================================
        # SECTION 4: General
        # ==========================================
        group_general = QGroupBox(tr("settings.group.general"))
        form_general = QFormLayout(group_general)
        form_general.setContentsMargins(10, 15, 10, 10)
        form_general.setVerticalSpacing(4)

        self.auto_start = QCheckBox()
        self.auto_start.setChecked(self.is_auto_start_enabled())
        form_general.addRow(tr("settings.label.auto_start"), self.auto_start)

        self.out_format = QComboBox()
        self.out_format.addItems(["PNG", "JPG"])
        self.out_format.setCurrentText(self.settings.value("out_format", "PNG"))
        form_general.addRow(tr("settings.label.out_format"), self.out_format)

        self.out_quality = QSpinBox()
        self.out_quality.setRange(1, 100)
        self.out_quality.setValue(int(self.settings.value("out_quality", 100)))
        form_general.addRow(tr("settings.label.out_quality"), self.out_quality)

        # Language selector
        self.lang_combo = QComboBox()
        self.lang_combo.addItems([tr("lang.es"), tr("lang.en")])
        current_lang = self.settings.value("language", "es")
        if current_lang == "en":
            self.lang_combo.setCurrentText(tr("lang.en"))
        else:
            self.lang_combo.setCurrentText(tr("lang.es"))
        form_general.addRow(tr("settings.label.language"), self.lang_combo)

        # Theme selector
        self.theme_combo = QComboBox()
        self.theme_combo.addItems([tr("theme.auto"), tr("theme.light"), tr("theme.dark")])
        current_theme = self.settings.value("theme", "auto")
        theme_map = {"auto": tr("theme.auto"), "light": tr("theme.light"), "dark": tr("theme.dark")}
        self.theme_combo.setCurrentText(theme_map.get(current_theme, tr("theme.auto")))
        form_general.addRow(tr("settings.label.theme"), self.theme_combo)

        # JPG quality enable/disable logic
        self.out_format.currentTextChanged.connect(self.update_quality_state)
        self.update_quality_state(self.out_format.currentText())

        layout.addWidget(group_general)

        # ==========================================
        # FINAL ASSEMBLY
        # ==========================================
        scroll_area.setWidget(container)
        main_layout.addWidget(scroll_area)

        # Buttons (outside scroll, always visible)
        btn_layout = QHBoxLayout()
        btn_defaults = QPushButton(tr("settings.btn.restore"))
        btn_defaults.clicked.connect(self.restore_defaults)
        btn_cancel = QPushButton(tr("settings.btn.cancel"))
        btn_cancel.setMinimumWidth(90)
        btn_cancel.clicked.connect(self.reject)
        btn_save = QPushButton(tr("settings.btn.save"))
        btn_save.setDefault(True)
        btn_save.setMinimumWidth(90)
        btn_save.clicked.connect(self.save_settings)
        btn_layout.addWidget(btn_defaults)
        btn_layout.addStretch()
        btn_layout.addWidget(btn_cancel)
        btn_layout.addWidget(btn_save)

        main_layout.addLayout(btn_layout)

        # Verificar conflictos iniciales
        self.check_modifier_conflicts()

    def update_quality_state(self, fmt):
        self.out_quality.setEnabled(fmt == "JPG")

    def browse_dir(self):
        dir_path = QFileDialog.getExistingDirectory(self, tr("dialog.select_dir"), self.save_dir.text())
        if dir_path:
            self.save_dir.setText(dir_path)



    def browse_editor(self):
        path, _ = QFileDialog.getOpenFileName(self, tr("dialog.select_editor"), "", 
                                               tr("dialog.file_filter_exe"))
        if path:
            self.editor_path.setText(path)

    def paste_url(self):
        clipboard = QApplication.clipboard()
        text = clipboard.text().strip()
        if text:
            parsed = urlparse(text)
            if parsed.scheme in ('http', 'https', 'ftp'):
                self.editor_path.setText(text)
            else:
                QMessageBox.information(
                    self,
                    tr("warn.not_url"),
                    tr("warn.not_url_msg"),
                    QMessageBox.StandardButton.Ok
                )

    def update_auto_state(self, action):
        is_save = (action == "Guardar")
        self.save_dir.setEnabled(is_save)
        self.btn_browse.setEnabled(is_save)
        
        is_open = (action == "Abrir")
        self.editor_path.setEnabled(is_open)
        self.btn_editor_browse.setEnabled(is_open)

    def save_settings(self):
        # Verify modifier conflicts before saving
        mods = {
            self.mod_lock.currentText(): "Bloquear proporción",
            self.mod_prop.currentText(): "Forzar preferidas", 
            self.mod_inv_prop.currentText(): "Invertir preferidas"
        }
        
        # Eliminar "---" del diccionario
        mods = {k: v for k, v in mods.items() if k != "---"}
        
        if len(mods) != len(set(mods.keys())):
            QMessageBox.warning(
                self, 
                tr("warn.modifier_conflict"),
                tr("warn.modifier_conflict_msg"),
                QMessageBox.StandardButton.Ok
            )
            return
        
        editor_path = self.editor_path.text().strip()
        if editor_path:
            parsed = urlparse(editor_path)
            is_url = parsed.scheme in ('http', 'https', 'ftp')
            is_valid_path = os.path.isfile(editor_path)

            if not (is_url or is_valid_path):
                QMessageBox.warning(
                    self,
                    tr("warn.invalid_path"),
                    tr("warn.invalid_path_msg", path=editor_path),
                    QMessageBox.StandardButton.Ok
                )
                return
        
        self.settings.setValue("hotkey_zone", self.hk_zone.text())
        self.settings.setValue("hotkey_full", self.hk_full.text())
        self.settings.setValue("hotkey_silent", self.hk_silent.text())
        self.settings.setValue("mod_lock", self.mod_lock.currentText())
        self.settings.setValue("mod_prop", self.mod_prop.currentText())
        self.settings.setValue("mod_inv_prop", self.mod_inv_prop.currentText())
        self.settings.setValue("prop_w", self.prop_w.value())
        self.settings.setValue("prop_h", self.prop_h.value())
        self.settings.setValue("zoom_enabled", self.zoom_enabled.isChecked())
        self.settings.setValue("default_zoom", self.default_zoom.value())
        self.settings.setValue("default_mag_size", self.default_mag_size.value())
        self.settings.setValue("show_coords", self.show_coords.isChecked())
        self.settings.setValue("auto_action", self.auto_action.currentData())
        self.settings.setValue("editor_path", editor_path)
        self.settings.setValue("save_dir", self.save_dir.text())
        self.settings.setValue("out_format", self.out_format.currentText())
        self.settings.setValue("out_quality", self.out_quality.value())
        self.set_auto_start(self.auto_start.isChecked())
        # Save language
        new_lang = "en" if self.lang_combo.currentText() == tr("lang.en") else "es"
        old_lang = self.settings.value("language", "es")
        self.settings.setValue("language", new_lang)
        # Save theme
        theme_reverse = {tr("theme.auto"): "auto", tr("theme.light"): "light", tr("theme.dark"): "dark"}
        new_theme = theme_reverse.get(self.theme_combo.currentText(), "auto")
        self.settings.setValue("theme", new_theme)
        ThemeManager.instance().set_theme(new_theme)
        self.accept()
        # Restart if language changed so all strings reload
        if new_lang != old_lang:
            logging.info("Language changed, restarting")
            os.execl(sys.executable, sys.executable, *sys.argv)

    def keyPressEvent(self, event):
        if event.key() in (Qt.Key.Key_Return, Qt.Key.Key_Enter):
            self.save_settings()
        else:
            super().keyPressEvent(event)

    def restore_defaults(self):
        self.hk_zone.line_edit.setText("print screen")
        self.hk_full.line_edit.setText("shift+print screen")
        self.hk_silent.line_edit.setText("ctrl+print screen")
        self.mod_lock.setCurrentText("Ctrl")
        self.mod_prop.setCurrentText("Shift")
        self.mod_inv_prop.setCurrentText("Alt")
        self.prop_w.setValue(9)
        self.prop_h.setValue(16)
        self.zoom_enabled.setChecked(True)
        self.default_zoom.setValue(4)
        self.default_mag_size.setValue(120)
        self.show_coords.setChecked(True)
        for i in range(self.auto_action.count()):
            if self.auto_action.itemData(i) == "Guardar":
                self.auto_action.setCurrentIndex(i)
                break
        self.editor_path.setText("")
        self.save_dir.setText(os.path.expanduser('~'))
        self.out_format.setCurrentText("PNG")
        self.out_quality.setValue(100)
        self.lang_combo.setCurrentText(tr("lang.es"))
        self.theme_combo.setCurrentText(tr("theme.auto"))

    def get_run_key(self):
        return r"Software\Microsoft\Windows\CurrentVersion\Run"

    def _current_exe_path(self):
        if getattr(sys, 'frozen', False):
            return sys.executable
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'dist', 'captura.exe')
        if not os.path.exists(path):
            path = os.path.abspath(sys.argv[0])
        return path

    def is_auto_start_enabled(self):
        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, self.get_run_key(), 0, winreg.KEY_READ) as key:
                val, _ = winreg.QueryValueEx(key, "CapturaKdgdkd")
                stored = val.strip('"')
                return os.path.normcase(stored) == os.path.normcase(self._current_exe_path())
        except FileNotFoundError:
            return False

    def set_auto_start(self, enable):
        try:
            key = winreg.OpenKey(winreg.HKEY_CURRENT_USER, self.get_run_key(), 0, winreg.KEY_ALL_ACCESS)
            if enable:
                exe_path = self._current_exe_path()
                winreg.SetValueEx(key, "CapturaKdgdkd", 0, winreg.REG_SZ, f'"{exe_path}"')
            else:
                try:
                    winreg.DeleteValue(key, "CapturaKdgdkd")
                except FileNotFoundError:
                    pass
            winreg.CloseKey(key)
        except Exception as e:
            logging.error("Error configurando auto-inicio: %s", e)

class SignalBridge(QObject):
    trigger_capture = pyqtSignal()
    trigger_full = pyqtSignal()
    trigger_silent = pyqtSignal()

class CaptureOverlay(QWidget):

    @property
    def FEEDBACK_STYLE(self):
        return feedback_qss(ThemeManager.instance().palette)


    def __init__(self, full_screenshot, tray_icon=None):
        super().__init__()
        self.setAttribute(Qt.WidgetAttribute.WA_DeleteOnClose)
        self.full_screenshot = full_screenshot
        self.ratio = self.full_screenshot.devicePixelRatio()
        self.tray_icon = tray_icon
        
        self.setWindowFlags(Qt.WindowType.FramelessWindowHint | 
                            Qt.WindowType.WindowStaysOnTopHint | 
                            Qt.WindowType.Tool)
        self.setWindowState(Qt.WindowState.WindowFullScreen)
        self.setMouseTracking(True)
        self.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.activateWindow()
        self.raise_()
        self.begin = QPoint()
        self.end = QPoint()
        self.current_pos = QPoint()
        self.is_selecting = False
        self.selection_rect = QRect()
        
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        self.zoom = int(settings.value("default_zoom", 4))
        self.mag_size = int(settings.value("default_mag_size", 120))
        # Cache paintEvent flags: reading QSettings on every repaint
        # (every mouse move) would hit the Windows registry in a tight loop.
        self.zoom_enabled = settings.value("zoom_enabled", True, type=bool)
        self.show_coords = settings.value("show_coords", True, type=bool)
        self._auto_action = settings.value("auto_action", "Guardar")

        # Cache modifier config to avoid QSettings reads on every repaint
        self._mod_lock, self._mod_pr, self._mod_inv_pr, self._prop_w_conf, self._prop_h_conf = \
            self._get_modifiers_config()

        # Standard ratios are defined in module-level STANDARD_RATIOS above

        self.mode = 'new_selection' 
        self.active_handle = None
        self.drag_offset = QPoint()
        self.resize_anchor = None  # Fixed opposite corner during resize
        
        self.panel = QWidget(self)
        self.panel.setStyleSheet(panel_qss(ThemeManager.instance().palette))
        
        layout = QHBoxLayout(self.panel)
        layout.setContentsMargins(6, 6, 6, 6)
        layout.setSpacing(6)
        
        icon_size = 18

        palette = ThemeManager.instance().palette

        self.icon_auto_light = self.create_svg_icon(ICON_AUTO, palette.icon_light, icon_size)
        self.icon_copy_light = self.create_svg_icon(ICON_COPY, palette.icon_light, icon_size)
        self.icon_save_light = self.create_svg_icon(ICON_SAVE, palette.icon_light, icon_size)
        self.icon_open_light = self.create_svg_icon(ICON_OPEN, palette.icon_light, icon_size)
        self.icon_cancel_light = self.create_svg_icon(ICON_CANCEL, palette.icon_light, icon_size)

        self.icon_auto_dark = self.create_svg_icon(ICON_AUTO, palette.icon_dark, icon_size)
        self.icon_copy_dark = self.create_svg_icon(ICON_COPY, palette.icon_dark, icon_size)
        self.icon_save_dark = self.create_svg_icon(ICON_SAVE, palette.icon_dark, icon_size)
        self.icon_open_dark = self.create_svg_icon(ICON_OPEN, palette.icon_dark, icon_size)
        self.icon_cancel_dark = self.create_svg_icon(ICON_CANCEL, palette.icon_dark, icon_size)


        _auto_action = self._auto_action

        self.btn_auto = None
        if _auto_action and _auto_action != "---":
            _auto_icon_map = {
                "Guardar": (self.icon_save_light, self.icon_save_dark),
                "Copiar":  (self.icon_copy_light, self.icon_copy_dark),
                "Abrir":   (self.icon_open_light, self.icon_open_dark),
            }
            _auto_icons = _auto_icon_map.get(_auto_action, (self.icon_auto_light, self.icon_auto_dark))

            self.btn_auto = QPushButton()
            self.install_icon_swap(self.btn_auto, _auto_icons[0], _auto_icons[1])
            self.btn_auto.setIconSize(QSize(icon_size, icon_size))
            self.btn_auto.setToolTip(tr("overlay.auto_tip", action=_auto_action))
            self.btn_auto.setCursor(Qt.CursorShape.PointingHandCursor)
            self.btn_auto.clicked.connect(self.on_auto_clicked)
            layout.addWidget(self.btn_auto)

        self.btn_copy = QPushButton()
        self.install_icon_swap(self.btn_copy, self.icon_copy_light, self.icon_copy_dark)
        self.btn_copy.setIconSize(QSize(icon_size, icon_size))
        self.btn_copy.setToolTip(tr("overlay.copy_tip"))
        self.btn_copy.setCursor(Qt.CursorShape.PointingHandCursor)

        self.btn_save = QPushButton()
        self.install_icon_swap(self.btn_save, self.icon_save_light, self.icon_save_dark)
        self.btn_save.setIconSize(QSize(icon_size, icon_size))
        self.btn_save.setToolTip(tr("overlay.save_tip"))
        self.btn_save.setCursor(Qt.CursorShape.PointingHandCursor)

        self.btn_open = QPushButton()
        self.install_icon_swap(self.btn_open, self.icon_open_light, self.icon_open_dark)
        self.btn_open.setIconSize(QSize(icon_size, icon_size))
        self.btn_open.setToolTip(tr("overlay.open_tip"))
        self.btn_open.setCursor(Qt.CursorShape.PointingHandCursor)

        self.btn_cancel = QPushButton()
        self.install_icon_swap(self.btn_cancel, self.icon_cancel_light, self.icon_cancel_dark)
        self.btn_cancel.setIconSize(QSize(icon_size, icon_size))
        self.btn_cancel.setToolTip(tr("overlay.cancel_tip"))
        self.btn_cancel.setCursor(Qt.CursorShape.PointingHandCursor)
        
        self.btn_cancel.setStyleSheet(cancel_btn_qss(palette))
            
        layout.addWidget(self.btn_copy)
        layout.addWidget(self.btn_save)
        layout.addWidget(self.btn_open)
        layout.addWidget(self.btn_cancel)
        
        self.btn_copy.clicked.connect(self.on_copy_clicked)
        self.btn_save.clicked.connect(self.on_save_clicked)
        self.btn_open.clicked.connect(self.on_open_with_clicked)
        self.btn_cancel.clicked.connect(self.close)

        # Drag & drop desde el panel hacia otras aplicaciones
        self._drag_start_pos = None
        _drag_widgets = [self.panel, self.btn_copy, self.btn_save,
                         self.btn_open, self.btn_cancel]
        if self.btn_auto is not None:
            _drag_widgets.append(self.btn_auto)
        for w in _drag_widgets:
            w.installEventFilter(self)

        self.panel.hide()

    def install_icon_swap(self, button, icon_normal, icon_hover):
        button.setIcon(icon_normal)
        button._icon_normal = icon_normal
        button._icon_hover = icon_hover
        button.enterEvent = lambda e: button.setIcon(button._icon_hover)
        button.leaveEvent = lambda e: button.setIcon(button._icon_normal)

    def eventFilter(self, obj, event):
        _drag_targets = [self.panel, self.btn_copy, self.btn_save,
                         self.btn_open, self.btn_cancel]
        if self.btn_auto is not None:
            _drag_targets.append(self.btn_auto)
        if obj in _drag_targets:
            t = event.type()
            if t == QEvent.Type.MouseButtonPress and event.button() == Qt.MouseButton.LeftButton:
                self._drag_start_pos = event.globalPosition().toPoint()
            elif t == QEvent.Type.MouseMove and self._drag_start_pos is not None:
                delta = event.globalPosition().toPoint() - self._drag_start_pos
                if delta.manhattanLength() >= QApplication.startDragDistance():
                    self._drag_start_pos = None
                    self._start_drag()
                    return True
            elif t == QEvent.Type.MouseButtonRelease:
                self._drag_start_pos = None
        return super().eventFilter(obj, event)

    def _start_drag(self):
        if self.selection_rect.isNull():
            return
        pixmap = self.get_cropped_pixmap()
        temp_path = new_temp_image_path(".png")
        pixmap.save(temp_path, format="PNG")

        drag = QDrag(self)
        mime = QMimeData()
        mime.setImageData(pixmap.toImage())
        mime.setUrls([QUrl.fromLocalFile(temp_path)])
        drag.setMimeData(mime)

        thumb = pixmap.scaled(120, 90, Qt.AspectRatioMode.KeepAspectRatio,
                              Qt.TransformationMode.SmoothTransformation)
        drag.setPixmap(thumb)
        drag.setHotSpot(QPoint(thumb.width() // 2, thumb.height() // 2))
        drag.exec(Qt.DropAction.CopyAction)

    def create_svg_icon(self, svg_string: str, color: str = "#ffffff",
                         size: int = 18) -> QIcon:
        """Convierte un string SVG en un QIcon con un color específico"""
        colored_svg = svg_string.replace('stroke="currentColor"', f'stroke="{color}"')
        
        pixmap = QPixmap(size, size)
        pixmap.fill(Qt.GlobalColor.transparent)
        renderer = QSvgRenderer(bytes(colored_svg, 'utf-8'))
        painter = QPainter(pixmap)
        renderer.render(painter)
        painter.end()
        return QIcon(pixmap)

    def get_ratio_info(self, w: int, h: int) -> Optional[Tuple[str, str]]:
        return _compute_ratio_info(w, h)
    
    def get_current_dimensions(self) -> Tuple[int, int]:
        if self.mode == 'new_selection' and self.is_selecting:
            return abs(self.current_pos.x() - self.begin.x()), abs(self.current_pos.y() - self.begin.y())
        elif self.mode == 'resizing' and self.is_selecting and self.resize_anchor is not None:
            return abs(self.current_pos.x() - self.resize_anchor.x()), abs(self.current_pos.y() - self.resize_anchor.y())
        elif not self.selection_rect.isNull():
            return self.selection_rect.width(), self.selection_rect.height()
        return 0, 0

    def get_handle_at(self, pos: QPoint) -> Optional[str]:
        if self.selection_rect.isNull():
            return None
        HANDLE_SIZE = 12
        r = self.selection_rect
        handles = {
            'top_left': QRect(r.left() - HANDLE_SIZE//2, r.top() - HANDLE_SIZE//2, HANDLE_SIZE, HANDLE_SIZE),
            'top_right': QRect(r.right() - HANDLE_SIZE//2, r.top() - HANDLE_SIZE//2, HANDLE_SIZE, HANDLE_SIZE),
            'bottom_left': QRect(r.left() - HANDLE_SIZE//2, r.bottom() - HANDLE_SIZE//2, HANDLE_SIZE, HANDLE_SIZE),
            'bottom_right': QRect(r.right() - HANDLE_SIZE//2, r.bottom() - HANDLE_SIZE//2, HANDLE_SIZE, HANDLE_SIZE)
        }
        for name, rect in handles.items():
            if rect.contains(pos):
                return name
        return None

    def paintEvent(self, event):
        painter = QPainter(self)
        p = ThemeManager.instance().palette
        logical_rect = self.rect()
        painter.drawPixmap(logical_rect, self.full_screenshot)
        painter.fillRect(logical_rect, p.overlay_dim)

        zoom_enabled = self.zoom_enabled
        show_coords = self.show_coords

        handle = self.get_handle_at(self.current_pos)
        show_lupa = False
        
        if zoom_enabled:
            if self.mode in ['new_selection', 'resizing']:
                show_lupa = True
            elif not self.is_selecting:
                if self.selection_rect.isNull() or handle is not None or not self.selection_rect.contains(self.current_pos):
                    show_lupa = True

        if not self.selection_rect.isNull():
            painter.drawPixmap(self.selection_rect, self.full_screenshot, 
                               QRect(self.selection_rect.topLeft() * self.ratio, 
                                     self.selection_rect.size() * self.ratio))
            pen = QPen(p.selection_border, 1)
            painter.setPen(pen)
            painter.drawRect(self.selection_rect)
            
            painter.setBrush(QColor(p.selection_handle))
            painter.setPen(QPen(Qt.GlobalColor.white, 1))
            h_size = 8
            pts = [self.selection_rect.topLeft(), self.selection_rect.topRight(), 
                   self.selection_rect.bottomLeft(), self.selection_rect.bottomRight()]
            for pt in pts:
                painter.drawRect(pt.x() - h_size//2, pt.y() - h_size//2, h_size, h_size)

            w_px = int(self.selection_rect.width() * self.ratio)
            h_px = int(self.selection_rect.height() * self.ratio)
            
            ratio_info = self.get_ratio_info(w_px, h_px)
            
            if ratio_info:
                ratio_text, sign = ratio_info
                text = f"{w_px} × {h_px}  |  {ratio_text}{sign}"
            else:
                text = f"{w_px} × {h_px}"
            
            font = QFont("Arial", 8)
            painter.setFont(font)
            fm = QFontMetrics(font)
            text_w = fm.horizontalAdvance(text)
            text_h = fm.height()
            
            padding = 4
            bg_w = text_w + padding * 2
            bg_h = text_h + padding * 2
            
            x_pos = self.selection_rect.left()
            if x_pos + bg_w > self.width():
                x_pos = self.width() - bg_w
                
            y_pos = self.selection_rect.top() - bg_h - 4
            if y_pos < 0:
                y_pos = self.selection_rect.bottom() + 4
                if y_pos + bg_h > self.height():
                    y_pos = self.selection_rect.bottom() - bg_h - 4

            bg_rect = QRect(x_pos, y_pos, bg_w, bg_h)
            painter.setPen(Qt.PenStyle.NoPen)
            painter.setBrush(p.dimension_label_bg)
            painter.drawRect(bg_rect)
            
            painter.setPen(p.dimension_label_text)
            painter.drawText(bg_rect, Qt.AlignmentFlag.AlignCenter, text)

            # Active modifier chip (only while drawing/resizing)
            if self.is_selecting and self.mode in ('new_selection', 'resizing'):
                modifiers = QApplication.keyboardModifiers()
                chip_text = None
                chip_color = p.modifier_chip_blocker
                if (self._mod_lock != Qt.KeyboardModifier.NoModifier
                        and modifiers & self._mod_lock):
                    ratio_info = self.get_ratio_info(w_px, h_px)
                    label = ratio_info[0] if ratio_info else "Libre"
                    chip_text = f"Bloqueado {label}"
                elif (self._mod_inv_pr != Qt.KeyboardModifier.NoModifier
                        and modifiers & self._mod_inv_pr):
                    chip_text = f"Invertido {self._prop_h_conf}:{self._prop_w_conf}"
                    chip_color = p.modifier_chip_inverted
                elif (self._mod_pr != Qt.KeyboardModifier.NoModifier
                        and modifiers & self._mod_pr):
                    chip_text = f"Forzado {self._prop_w_conf}:{self._prop_h_conf}"
                    chip_color = p.modifier_chip_forced

                if chip_text:
                    chip_font = QFont("Arial", 7)
                    painter.setFont(chip_font)
                    cfm = QFontMetrics(chip_font)
                    cw = cfm.horizontalAdvance(chip_text) + 10
                    ch = cfm.height() + 6
                    cx = bg_rect.right() + 6
                    cy = bg_rect.top()
                    if cx + cw > self.width():
                        cx = bg_rect.left() - cw - 6
                    chip_rect = QRect(cx, cy, cw, ch)
                    painter.setPen(Qt.PenStyle.NoPen)
                    painter.setBrush(chip_color)
                    painter.drawRoundedRect(chip_rect, 4, 4)
                    painter.setPen(p.chip_text)
                    painter.drawText(chip_rect, Qt.AlignmentFlag.AlignCenter, chip_text)

        if show_lupa and not self.current_pos.isNull():
            pen = QPen(p.crosshair_lines, 1, Qt.PenStyle.SolidLine)
            painter.setPen(pen)
            painter.drawLine(0, self.current_pos.y(), self.width(), self.current_pos.y())
            painter.drawLine(self.current_pos.x(), 0, self.current_pos.x(), self.height())

            mag_size = self.mag_size
            zoom = self.zoom
            offset = 40
            
            possible_points = [
                (self.current_pos.x() + offset, self.current_pos.y() + offset),
                (self.current_pos.x() - offset - mag_size, self.current_pos.y() + offset),
                (self.current_pos.x() + offset, self.current_pos.y() - offset - mag_size),
                (self.current_pos.x() - offset - mag_size, self.current_pos.y() - offset - mag_size)
            ]
            
            target_rect = None
            for tx, ty in possible_points:
                rect = QRect(tx, ty, mag_size, mag_size)
                in_screen = rect.left() >= 0 and rect.top() >= 0 and \
                            rect.right() <= self.width() and rect.bottom() <= self.height()
                if in_screen and not rect.intersects(self.selection_rect):
                    target_rect = rect
                    break
            
            if target_rect is None:
                for tx, ty in possible_points:
                    rect = QRect(tx, ty, mag_size, mag_size)
                    if rect.left() >= 0 and rect.top() >= 0 and \
                       rect.right() <= self.width() and rect.bottom() <= self.height():
                        target_rect = rect
                        break
            
            if target_rect is None:
                target_rect = QRect(self.current_pos.x() + offset, self.current_pos.y() + offset, mag_size, mag_size)

            # Dibujar coordenadas encima de la lupa
            if show_coords:
                coord_text = f"X: {self.current_pos.x()} Y: {self.current_pos.y()}"
                painter.setFont(QFont("Arial", 7))
                fm = painter.fontMetrics()
                tw = fm.horizontalAdvance(coord_text)
                th = fm.height()
                
            # Show coordinates above the magnifier
                tx = target_rect.center().x() - tw // 2
                ty = target_rect.top() - 5
                
                # Small background for readability
                painter.setPen(Qt.PenStyle.NoPen)
                painter.setBrush(p.coord_text_bg)
                painter.drawRect(tx - 2, ty - th + 2, tw + 4, th)
                
                painter.setPen(p.coord_text)
                painter.drawText(tx, ty, coord_text)

            src_w = mag_size // zoom
            src_h = mag_size // zoom
            src_rect = QRect(0, 0, src_w, src_h)
            src_rect.moveCenter(self.current_pos)
            src_rect = src_rect.intersected(self.rect())

            physical_src_rect = QRect(src_rect.topLeft() * self.ratio, src_rect.size() * self.ratio)
            magnified_pixmap = self.full_screenshot.copy(physical_src_rect)
            
            painter.save()
            path = QPainterPath()
            path.addEllipse(target_rect.toRectF())
            painter.setClipPath(path)
            painter.drawPixmap(target_rect, magnified_pixmap)
            painter.restore()
            
            painter.setPen(QPen(QColor(p.magnifier_border), 1))
            painter.drawEllipse(target_rect)
            
            painter.setPen(QPen(p.magnifier_crosshair, 1))
            center = target_rect.center()
            cross_size = 30
            painter.drawLine(center.x() - cross_size, center.y(), center.x() + cross_size, center.y())
            painter.drawLine(center.x(), center.y() - cross_size, center.x(), center.y() + cross_size)

    def mousePressEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            self.current_pos = event.pos()
            
            if not self.selection_rect.isNull():
                handle = self.get_handle_at(self.current_pos)
                if handle:
                    self.mode = 'resizing'
                    self.active_handle = handle
                    # Capture the opposite corner NOW and keep it fixed during drag
                    self.resize_anchor = self._anchor_for_handle(handle)
                    self.is_selecting = True
                    self.panel.hide()
                    return
                elif self.selection_rect.contains(self.current_pos):
                    self.mode = 'moving'
                    self.drag_offset = self.current_pos - self.selection_rect.topLeft()
                    self.is_selecting = True
                    self.setCursor(Qt.CursorShape.ClosedHandCursor)
                    self.panel.hide()
                    return
                else:
                    self.selection_rect = QRect()
                    self.panel.hide()
            
            self.mode = 'new_selection'
            self.begin = event.pos()
            self.end = self.begin
            self.is_selecting = True
            self.panel.hide()
            self.update()
            
        elif event.button() == Qt.MouseButton.RightButton:
            self.close()

    def _get_modifiers_config(self):
        """Devuelve (mod_lock, mod_pr, mod_inv_prop, prop_w, prop_h) leyendo settings."""
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        mod_lock_str = settings.value("mod_lock", "Ctrl")
        mod_pr_str = settings.value("mod_prop", "Shift")
        mod_inv_pr_str = settings.value("mod_inv_prop", "Alt")

        def str_to_mod(s):
            if s == "Shift": return Qt.KeyboardModifier.ShiftModifier
            if s == "Alt": return Qt.KeyboardModifier.AltModifier
            if s == "Ctrl": return Qt.KeyboardModifier.ControlModifier
            return Qt.KeyboardModifier.NoModifier

        mod_lock = str_to_mod(mod_lock_str)
        mod_pr = str_to_mod(mod_pr_str)
        mod_inv_pr = str_to_mod(mod_inv_pr_str)
        prop_w = int(settings.value("prop_w", 9))
        prop_h = int(settings.value("prop_h", 16))
        return mod_lock, mod_pr, mod_inv_pr, prop_w, prop_h

    def _constrain_endpoint(self, anchor: QPoint, cursor: QPoint,
                            modifiers: Qt.KeyboardModifier) -> QPoint:
        mod_lock, mod_pr, mod_inv_pr, prop_w, prop_h = self._get_modifiers_config()

        dx = cursor.x() - anchor.x()
        dy = cursor.y() - anchor.y()

        if dx == 0 and dy == 0:
            return QPoint(cursor)

        sign_x = 1 if dx >= 0 else -1
        sign_y = 1 if dy >= 0 else -1
        abs_dx = abs(dx)
        abs_dy = abs(dy)

        # Lock to the currently displayed ratio (Ctrl by default)
        if modifiers & mod_lock:
            ratio_info = self.get_current_ratio()
            
            if ratio_info:
                ratio_text, _ = ratio_info
                
                parts = ratio_text.split(':')
                if len(parts) == 2:
                    target_w = float(parts[0])
                    target_h = float(parts[1])
                    target_ratio = target_w / target_h
                    
                    # The cursor defines one side of the rectangle.
                    # Option 1: cursor on horizontal edge (same Y, X computed from ratio)
                    # Option 2: cursor on vertical edge (same X, Y computed from ratio)
                    # For option 1: height = |dy|, width = height * ratio
                    # For option 2: width = |dx|, height = width / ratio
                    # Choose the option that makes the rectangle larger
                    # (cursor is on the edge farthest from the anchor)
                    
                    option1_width = abs_dy * target_ratio
                    option2_height = abs_dx / target_ratio
                    
                    # Cursor defines the edge that maximizes rectangle area
                    if option1_width * abs_dy >= abs_dx * option2_height:
                        if option1_width >= abs_dx:
                            return QPoint(anchor.x() + int(option1_width) * sign_x, cursor.y())
                        else:
                            return QPoint(cursor.x(), anchor.y() + int(abs_dx / target_ratio) * sign_y)
                    else:
                        if option2_height >= abs_dy:
                            return QPoint(cursor.x(), anchor.y() + int(option2_height) * sign_y)
                        else:
                            return QPoint(anchor.x() + int(abs_dy * target_ratio) * sign_x, cursor.y())
            
            return QPoint(cursor)
        
        # Lock to preferred ratio (Shift by default)
        is_inverted = (modifiers & mod_inv_pr)
        is_prop_active = (modifiers & mod_pr) or is_inverted
        
        if is_prop_active and prop_w > 0 and prop_h > 0:
            target_w = prop_h if is_inverted else prop_w
            target_h = prop_w if is_inverted else prop_h
            
            if abs_dx / target_w > abs_dy / target_h:
                h = int(abs_dx * target_h / target_w)
                return QPoint(anchor.x() + dx, anchor.y() + h * sign_y)
            else:
                w = int(abs_dy * target_w / target_h)
                return QPoint(anchor.x() + w * sign_x, anchor.y() + dy)

        return QPoint(cursor)
    
    def get_current_ratio(self) -> Optional[Tuple[str, str]]:
        if self.selection_rect.isNull():
            return None
        w_px = int(self.selection_rect.width() * self.ratio)
        h_px = int(self.selection_rect.height() * self.ratio)
        return self.get_ratio_info(w_px, h_px)

    def _anchor_for_handle(self, handle: str) -> Optional[QPoint]:
        """Corner opposite to the active handle (serves as anchor during resize)."""
        r = self.selection_rect
        if handle == 'top_left':
            return r.bottomRight()
        if handle == 'top_right':
            return r.bottomLeft()
        if handle == 'bottom_left':
            return r.topRight()
        if handle == 'bottom_right':
            return r.topLeft()
        return None

    def update_selection(self):
        if not self.is_selecting or self.mode != 'new_selection':
            return

        modifiers = QApplication.keyboardModifiers()
        self.end = self._constrain_endpoint(self.begin, self.current_pos, modifiers)
        self.selection_rect = QRect(self.begin, self.end).normalized()

    def update_resize(self):
        """Recalcula selection_rect mientras se redimensiona, aplicando modificadores."""
        if not self.is_selecting or self.mode != 'resizing' or self.resize_anchor is None:
            return

        modifiers = QApplication.keyboardModifiers()
        new_corner = self._constrain_endpoint(self.resize_anchor, self.current_pos, modifiers)
        self.selection_rect = QRect(self.resize_anchor, new_corner).normalized()

    def mouseMoveEvent(self, event):
        self.current_pos = event.pos()
        
        if self.is_selecting:
            if self.mode == 'new_selection':
                self.update_selection()
            elif self.mode == 'moving':
                new_top_left = self.current_pos - self.drag_offset
                new_rect = QRect(new_top_left, self.selection_rect.size())
                
                if new_rect.left() < 0: new_rect.moveLeft(0)
                if new_rect.top() < 0: new_rect.moveTop(0)
                if new_rect.right() > self.width(): new_rect.moveRight(self.width())
                if new_rect.bottom() > self.height(): new_rect.moveBottom(self.height())
                
                self.selection_rect = new_rect
            elif self.mode == 'resizing':
                self.update_resize()
        else:
            if not self.selection_rect.isNull():
                handle = self.get_handle_at(self.current_pos)
                if handle in ['top_left', 'bottom_right']:
                    self.setCursor(Qt.CursorShape.SizeFDiagCursor)
                elif handle in ['top_right', 'bottom_left']:
                    self.setCursor(Qt.CursorShape.SizeBDiagCursor)
                elif self.selection_rect.contains(self.current_pos):
                    self.setCursor(Qt.CursorShape.OpenHandCursor)
                else:
                    self.setCursor(Qt.CursorShape.CrossCursor)
            else:
                self.setCursor(Qt.CursorShape.CrossCursor)
                
        self.update()

    def mouseReleaseEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            self.is_selecting = False
            if self.selection_rect.width() > 5 and self.selection_rect.height() > 5:
                if self.mode == 'moving':
                    self.setCursor(Qt.CursorShape.OpenHandCursor)
                self.show_export_menu(QCursor.pos())
            else:
                self.selection_rect = QRect()
                self.panel.hide()
                
            self.mode = None
            self.active_handle = None
            self.resize_anchor = None
            self.update()

    def wheelEvent(self, event):
        angle = event.angleDelta().y()
        modifiers = QApplication.keyboardModifiers()
        
        if modifiers & Qt.KeyboardModifier.ControlModifier:
            if angle > 0:
                self.mag_size = min(400, self.mag_size + 10)
            elif angle < 0:
                self.mag_size = max(60, self.mag_size - 10)
        else:
            if angle > 0:
                self.zoom = min(20, self.zoom + 1)
            elif angle < 0:
                self.zoom = max(1, self.zoom - 1)
        self.update()

    def keyPressEvent(self, event):
        key = event.key()
        
        if key == Qt.Key.Key_Escape:
            self.close()
            return

        # Shortcuts only work if there is an active selection and buttons are visible
        if not self.selection_rect.isNull() and self.panel.isVisible():
            if key in (Qt.Key.Key_G, Qt.Key.Key_S):
                self.on_save_clicked()
                return
            
            if key in (Qt.Key.Key_Return, Qt.Key.Key_Enter, Qt.Key.Key_C):
                self.on_copy_clicked()
                return

        # Update geometry when a modifier is pressed
        modifiers = QApplication.keyboardModifiers()
        mod_lock, _, _, _, _ = self._get_modifiers_config()
        
        # If the lock modifier was pressed, adjust to the current displayed ratio
        if modifiers & mod_lock and self.is_selecting:
            if self.mode == 'new_selection':
                self.update_selection()
            elif self.mode == 'resizing':
                self.update_resize()
        
        self.update()

    def keyReleaseEvent(self, event):
        # Update geometry when a modifier is released
        if self.is_selecting:
            if self.mode == 'new_selection':
                self.update_selection()
            elif self.mode == 'resizing':
                self.update_resize()
        self.update()

    def show_export_menu(self, pos: QPoint) -> None:
        self.panel.adjustSize()
        # Position below-right of selection
        x = self.selection_rect.right() - self.panel.width()
        y = self.selection_rect.bottom() + 10
        
        # Try above if it overflows bottom
        if y + self.panel.height() > self.height():
            y = self.selection_rect.top() - self.panel.height() - 10
            
        # Clamp within screen bounds
        if y < 0:
            y = 10
        if y + self.panel.height() > self.height():
            y = self.height() - self.panel.height() - 10
            
        if x < 0: x = 10
        if x + self.panel.width() > self.width():
            x = self.width() - self.panel.width() - 10
            
        self.panel.move(x, y)
        self.panel.show()

    def on_copy_clicked(self):
        self.btn_copy.setStyleSheet(self.FEEDBACK_STYLE)
        self.copy_to_clipboard()
        if self.tray_icon:
            self.tray_icon.showMessage(tr("notify.title"), tr("notify.copied"),
                                       QSystemTrayIcon.MessageIcon.Information, 2000)
        QTimer.singleShot(200, self.close)
        
    def on_auto_clicked(self):
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        action = settings.value("auto_action", "Guardar")
        
        if action == "Copiar":
            self.btn_auto.setStyleSheet(self.FEEDBACK_STYLE)
            self.copy_to_clipboard()
            if self.tray_icon:
                self.tray_icon.showMessage(tr("notify.title"), tr("notify.copied"),
                                           QSystemTrayIcon.MessageIcon.Information, 2000)
            QTimer.singleShot(200, self.close)

        elif action == "Guardar":
            save_dir = settings.value("save_dir", os.path.expanduser('~'))
            fmt = settings.value("out_format", "PNG").lower()
            quality = int(settings.value("out_quality", 100))

            date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{date_str}_captura.{fmt}"
            path = os.path.join(save_dir, filename)

            os.makedirs(save_dir, exist_ok=True)

            if self.get_cropped_pixmap().save(path, format=fmt.upper(), quality=quality):
                logging.info("Auto-guardado en %s", path)
                self.btn_auto.setStyleSheet(self.FEEDBACK_STYLE)
                if self.tray_icon:
                    self.tray_icon.showMessage(tr("notify.saved"), path,
                                               QSystemTrayIcon.MessageIcon.Information, 3000)
                QTimer.singleShot(200, self.close)
            else:
                logging.error("Error al auto-guardar en %s", path)
                
        elif action == "Abrir":
            editor_path = settings.value("editor_path", "")
            
            parsed = urlparse(editor_path) if editor_path else None
            is_url = parsed and parsed.scheme in ('http', 'https', 'ftp')

            if is_url:
                self.copy_to_clipboard()
                logging.info("Imagen copiada al portapapeles. Abriendo URL.")
                self.btn_auto.setStyleSheet(self.FEEDBACK_STYLE)
                webbrowser.open(editor_path)
                QTimer.singleShot(200, self.close)
                
            elif editor_path and os.path.exists(editor_path):
                # Save to temp file and open with configured editor
                temp_path = new_temp_image_path()

                if self.get_cropped_pixmap().save(temp_path, format="PNG"):
                    self.btn_auto.setStyleSheet(self.FEEDBACK_STYLE)
                    subprocess.Popen([editor_path, temp_path])
                    QTimer.singleShot(200, self.close)
                else:
                    logging.error("Error al guardar archivo temporal para abrir la imagen")
            else:
                # No editor configured or invalid path — use native dialog
                temp_path = new_temp_image_path()

                if self.get_cropped_pixmap().save(temp_path, format="PNG"):
                    self.btn_auto.setStyleSheet(self.FEEDBACK_STYLE)
                    if os.name == 'nt':
                        subprocess.Popen(['rundll32.exe', 'shell32.dll,OpenAs_RunDLL', temp_path])
                    QTimer.singleShot(200, self.close)
                else:
                    logging.error("Error al guardar archivo temporal para abrir la imagen")


    def on_save_clicked(self):
        if self.save_to_file():
            self.btn_save.setStyleSheet(self.FEEDBACK_STYLE)
            QTimer.singleShot(200, self.close)


    def on_open_with_clicked(self):
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        editor_path = settings.value("editor_path", "")
        
        parsed = urlparse(editor_path) if editor_path else None
        is_url = parsed and parsed.scheme in ('http', 'https', 'ftp')

        if is_url:
            self.copy_to_clipboard()
            logging.info("Imagen copiada al portapapeles. Abriendo URL.")
            self.btn_open.setStyleSheet(self.FEEDBACK_STYLE)
            webbrowser.open(editor_path)
            QTimer.singleShot(200, self.close)
        else:
            # Original behaviour for local files
            temp_path = new_temp_image_path()

            if self.get_cropped_pixmap().save(temp_path, format="PNG"):
                self.btn_open.setStyleSheet(self.FEEDBACK_STYLE)

                if os.name == 'nt':
                    subprocess.Popen(['rundll32.exe', 'shell32.dll,OpenAs_RunDLL', temp_path])

                QTimer.singleShot(200, self.close)
            else:
                logging.error("Error al guardar archivo temporal para abrir la imagen")

    def get_cropped_pixmap(self) -> QPixmap:
        physical_rect = QRect(self.selection_rect.topLeft() * self.ratio, 
                              self.selection_rect.size() * self.ratio)
        return self.full_screenshot.copy(physical_rect)

    def copy_to_clipboard(self):
        QApplication.clipboard().setPixmap(self.get_cropped_pixmap())
        logging.info("Copiado al portapapeles")

    def save_to_file(self) -> bool:
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        fmt = settings.value("out_format", "PNG").lower()
        quality = int(settings.value("out_quality", 100))
        save_dir = settings.value("save_dir", os.path.expanduser('~'))

        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        default_name = os.path.join(save_dir, f"{date_str}_captura.{fmt}")

        filter_str = "PNG (*.png);;JPG (*.jpg)" if fmt == "png" else "JPG (*.jpg);;PNG (*.png)"

        path, _ = QFileDialog.getSaveFileName(self, tr("dialog.save_title"), default_name, filter_str)
        if path:
            ext = os.path.splitext(path)[1].lower().lstrip('.')
            if ext not in ('png', 'jpg', 'jpeg'):
                ext = fmt
                path = f"{os.path.splitext(path)[0]}.{ext}"
            save_fmt = 'JPEG' if ext in ('jpg', 'jpeg') else 'PNG'
            save_quality = quality if save_fmt == 'JPEG' else -1
            self.get_cropped_pixmap().save(path, format=save_fmt, quality=save_quality)
            logging.info("Guardado en %s", path)
            return True
        return False

class ScreenshotApp:
    def __init__(self):
        if os.name == 'nt':
            import ctypes
            try:
                myappid = 'kdgdkd.captura.1.0' # ID arbitrario para la app
                ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
            except Exception:
                pass

        self.app = QApplication(sys.argv)
        self.app.setQuitOnLastWindowClosed(False)
        self.app.setWindowIcon(self.get_app_icon())

        # Load configured language
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        lang = settings.value("language", "es")
        Translator.instance().load_locale(lang)

        # Initialize theme
        theme_setting = settings.value("theme", "auto")
        ThemeManager.instance().set_theme(theme_setting)
        
        self.bridge = SignalBridge()
        self.bridge.trigger_capture.connect(self.start_capture)
        self.bridge.trigger_full.connect(self.capture_full_screen)
        self.bridge.trigger_silent.connect(self.silent_capture)
        
        self.settings_dialog = None
        
        self.setup_tray_icon()
        self.setup_hotkeys()
        
        logging.info("Herramienta iniciada")

    def _register_hotkey(self, combo, callback):
        if not combo:
            return
        try:
            keyboard.add_hotkey(combo, callback, suppress=True)
        except Exception as e:
            logging.warning("No se pudo suprimir atajo '%s': %s. Se intenta sin supresión.", combo, e)
            try:
                keyboard.add_hotkey(combo, callback)
            except Exception as e2:
                logging.error("Error al registrar atajo '%s': %s", combo, e2)

    def setup_hotkeys(self):
        keyboard.unhook_all()
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        hk_zone = settings.value("hotkey_zone", "print screen")
        hk_full = settings.value("hotkey_full", "shift+print screen")
        hk_silent = settings.value("hotkey_silent", "ctrl+print screen")

        # If both shortcuts share the same base key (e.g. "print screen" and
        # "shift+print screen"), handle them with a single manual hook.
        def parse_combo(combo):
            parts = [p.strip().lower() for p in combo.split('+') if p.strip()]
            mods = set(p for p in parts if p in ('ctrl', 'control', 'shift', 'alt', 'win', 'cmd'))
            # normalise
            mods = {'ctrl' if m == 'control' else m for m in mods}
            base = next((p for p in parts if p not in ('ctrl', 'control', 'shift', 'alt', 'win', 'cmd')), None)
            return base, mods

        base_zone, mods_zone = parse_combo(hk_zone)
        base_full, mods_full = parse_combo(hk_full)

        if base_zone and base_zone == base_full and mods_zone != mods_full:
            # Conflict: same base key, different modifier combination.
            # Use a single hook that decides which to fire based on modifier state.
            def on_base_key(event):
                if event.event_type != keyboard.KEY_DOWN:
                    return
                pressed_mods = set()
                if keyboard.is_pressed('shift'): pressed_mods.add('shift')
                if keyboard.is_pressed('ctrl'):  pressed_mods.add('ctrl')
                if keyboard.is_pressed('alt'):   pressed_mods.add('alt')
                if pressed_mods == mods_full:
                    self.bridge.trigger_full.emit()
                elif pressed_mods == mods_zone:
                    self.bridge.trigger_capture.emit()
            try:
                keyboard.on_press_key(base_zone, on_base_key, suppress=True)
            except Exception as e:
                logging.warning("No se pudo suprimir '%s': %s. Se intenta sin supresión.", base_zone, e)
                try:
                    keyboard.on_press_key(base_zone, on_base_key)
                except Exception as e2:
                    logging.error("Error al registrar hook para '%s': %s", base_zone, e2)
            self._register_hotkey(hk_silent, lambda: self.bridge.trigger_silent.emit())
            return

        # Caso normal: atajos independientes.
        self._register_hotkey(hk_zone, lambda: self.bridge.trigger_capture.emit())
        self._register_hotkey(hk_full, lambda: self.bridge.trigger_full.emit())
        self._register_hotkey(hk_silent, lambda: self.bridge.trigger_silent.emit())

    def create_placeholder_icon(self):
        p = ThemeManager.instance().palette
        pixmap = QPixmap(64, 64)
        pixmap.fill(Qt.GlobalColor.transparent)
        painter = QPainter(pixmap)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        painter.setBrush(QColor(p.placeholder_bg))
        painter.setPen(Qt.PenStyle.NoPen)
        painter.drawEllipse(4, 4, 56, 56)
        painter.setPen(QColor(p.placeholder_text))
        painter.setFont(QFont("Arial", 30, QFont.Weight.Bold))
        painter.drawText(pixmap.rect(), Qt.AlignmentFlag.AlignCenter, "S")
        painter.end()
        return QIcon(pixmap)

    def get_app_icon(self):
        if hasattr(sys, '_MEIPASS'):
            base_path = sys._MEIPASS
        else:
            base_path = os.path.dirname(os.path.abspath(__file__))
        icon_path = os.path.join(base_path, "captura.ico")
        
        if os.path.exists(icon_path):
            return QIcon(icon_path)
        else:
            return self.create_placeholder_icon()

    def setup_tray_icon(self):
        self.tray_icon = QSystemTrayIcon(self.get_app_icon(), self.app)
        self.app.setWindowIcon(self.get_app_icon())
        self.tray_icon.setToolTip(tr("app.tooltip"))
        
        tray_menu = QMenu()
        capture_action = tray_menu.addAction(tr("tray.area"))
        capture_action.triggered.connect(self.start_capture)

        full_capture_action = tray_menu.addAction(tr("tray.fullscreen"))
        full_capture_action.triggered.connect(self.capture_full_screen)

        silent_action = tray_menu.addAction(tr("tray.silent"))
        silent_action.triggered.connect(self.silent_capture)

        # --- Delayed capture submenu ---
        delay_menu = tray_menu.addMenu(tr("tray.delay"))
        for secs in (3, 5, 10):
            action = delay_menu.addAction(tr(f"tray.delay.{secs}s"))
            action.triggered.connect(lambda checked, s=secs: self._start_delayed_capture(s))

        # --- Active window capture ---
        window_action = tray_menu.addAction(tr("tray.window"))
        window_action.triggered.connect(self.capture_active_window)

        # --- Monitor-specific capture submenu ---
        monitor_menu = tray_menu.addMenu(tr("tray.monitor"))
        for i, screen in enumerate(QApplication.screens()):
            name = screen.name()
            geo = screen.geometry()
            label = f"{name} ({geo.width()}×{geo.height()})"
            action = monitor_menu.addAction(label)
            action.triggered.connect(lambda checked, s=screen: self.capture_monitor(s))

        tray_menu.addSeparator()
        
        settings_action = tray_menu.addAction(tr("tray.settings"))
        settings_action.triggered.connect(self.open_settings)
        
        restart_action = tray_menu.addAction(tr("tray.restart"))
        restart_action.triggered.connect(self.restart_app)
        
        tray_menu.addSeparator()
        quit_action = tray_menu.addAction(tr("tray.quit"))
        quit_action.triggered.connect(self.app.quit)
        
        self.tray_icon.setContextMenu(tray_menu)
        self.tray_icon.activated.connect(self.on_tray_activated)
        self.tray_icon.show()

    def open_settings(self):
        if self.settings_dialog is not None:
            self.settings_dialog.activateWindow()
            self.settings_dialog.raise_()
            return
            
        self.settings_dialog = SettingsDialog()
        # Explicitly set icon on the dialog window
        self.settings_dialog.setWindowIcon(self.get_app_icon())
        self.settings_dialog.finished.connect(self._handle_settings_finished)
        self.settings_dialog.show()

    def _handle_settings_finished(self):
        self.setup_hotkeys()
        self.settings_dialog = None

    def on_tray_activated(self, reason):
        if reason == QSystemTrayIcon.ActivationReason.Trigger:
            self.start_capture()

    def capture_full_screen(self):
        screen = QApplication.screenAt(QCursor.pos())
        if not screen:
            screen = self.app.primaryScreen()

        full_screenshot = screen.grabWindow(0)
        self.overlay = CaptureOverlay(full_screenshot, tray_icon=self.tray_icon)

        ratio = full_screenshot.devicePixelRatio()
        logical_w = int(full_screenshot.width() / ratio)
        logical_h = int(full_screenshot.height() / ratio)
        self.overlay.selection_rect = QRect(0, 0, logical_w, logical_h)

        self.overlay.show()
        self.overlay.show_export_menu(QCursor.pos())

    def silent_capture(self):
        settings = QSettings(SETTINGS_ORG, SETTINGS_APP)
        action = settings.value("auto_action", "Guardar")
        if action == "---":
            return

        screen = QApplication.screenAt(QCursor.pos())
        if not screen:
            screen = self.app.primaryScreen()
        pixmap = screen.grabWindow(0)

        if action == "Copiar":
            QApplication.clipboard().setPixmap(pixmap)
            self.tray_icon.showMessage(tr("notify.title"), tr("notify.silent_copied"),
                                       QSystemTrayIcon.MessageIcon.Information, 2000)

        elif action == "Guardar":
            save_dir = settings.value("save_dir", os.path.expanduser('~'))
            fmt = settings.value("out_format", "PNG").lower()
            quality = int(settings.value("out_quality", 100))
            os.makedirs(save_dir, exist_ok=True)
            date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = os.path.join(save_dir, f"{date_str}_captura.{fmt}")
            save_fmt = 'JPEG' if fmt == 'jpg' else 'PNG'
            save_quality = quality if save_fmt == 'JPEG' else -1
            if pixmap.save(path, format=save_fmt, quality=save_quality):
                logging.info("Captura silenciosa guardada en %s", path)
                self.tray_icon.showMessage(tr("notify.saved"), path,
                                           QSystemTrayIcon.MessageIcon.Information, 3000)
            else:
                logging.error("Error al guardar captura silenciosa en %s", path)

        elif action == "Abrir":
            temp_path = new_temp_image_path(".png")
            if pixmap.save(temp_path, format="PNG"):
                editor_path = settings.value("editor_path", "")
                parsed = urlparse(editor_path) if editor_path else None
                is_url = parsed and parsed.scheme in ('http', 'https', 'ftp')
                if is_url:
                    QApplication.clipboard().setPixmap(pixmap)
                    webbrowser.open(editor_path)
                elif editor_path and os.path.exists(editor_path):
                    subprocess.Popen([editor_path, temp_path])
                elif os.name == 'nt':
                    subprocess.Popen(['rundll32.exe', 'shell32.dll,OpenAs_RunDLL', temp_path])

    def restart_app(self):
        logging.info("Reiniciando herramienta")
        os.execl(sys.executable, sys.executable, *sys.argv)

    # ------------------------------------------------------------
    # Delayed capture
    # ------------------------------------------------------------
    def _start_delayed_capture(self, seconds: int):
        self.tray_icon.showMessage(tr("notify.delay.title"),
                                   tr("notify.delay.msg", seconds=seconds),
                                   QSystemTrayIcon.MessageIcon.Information, 2000)
        QTimer.singleShot(seconds * 1000, self.start_capture)

    # ------------------------------------------------------------
    # Active window capture (Windows only)
    # ------------------------------------------------------------
    def capture_active_window(self):
        if os.name != 'nt':
            self.start_capture()
            return

        import ctypes
        from ctypes import wintypes

        user32 = ctypes.windll.user32

        pt = wintypes.POINT()
        user32.GetCursorPos(ctypes.byref(pt))
        hwnd = user32.WindowFromPoint(pt.x, pt.y)

        if hwnd:
            owner = user32.GetAncestor(hwnd, 3)  # GA_ROOTOWNER
            if owner:
                hwnd = owner

        if not hwnd or not user32.IsWindowVisible(hwnd):
            self.start_capture()
            return

        rect = wintypes.RECT()
        if not user32.GetWindowRect(hwnd, ctypes.byref(rect)):
            self.start_capture()
            return

        win_w = rect.right - rect.left
        win_h = rect.bottom - rect.top
        if win_w <= 0 or win_h <= 0:
            self.start_capture()
            return

        screen = QApplication.screenAt(QPoint(rect.left, rect.top))
        if not screen:
            screen = self.app.primaryScreen()

        full_screenshot = screen.grabWindow(0)
        ratio = full_screenshot.devicePixelRatio()
        screen_geom = screen.geometry()
        physical_offset_x = screen_geom.x() * ratio
        physical_offset_y = screen_geom.y() * ratio

        logical_x = int((rect.left - physical_offset_x) / ratio)
        logical_y = int((rect.top - physical_offset_y) / ratio)
        logical_w = int(win_w / ratio)
        logical_h = int(win_h / ratio)

        self.overlay = CaptureOverlay(full_screenshot, tray_icon=self.tray_icon)
        self.overlay.selection_rect = QRect(logical_x, logical_y, logical_w, logical_h)
        self.overlay.show()
        self.overlay.show_export_menu(QCursor.pos())

    # ------------------------------------------------------------
    # Monitor-specific capture
    # ------------------------------------------------------------
    def capture_monitor(self, screen):
        full_screenshot = screen.grabWindow(0)
        self.overlay = CaptureOverlay(full_screenshot, tray_icon=self.tray_icon)

        ratio = full_screenshot.devicePixelRatio()
        logical_w = int(full_screenshot.width() / ratio)
        logical_h = int(full_screenshot.height() / ratio)
        self.overlay.selection_rect = QRect(0, 0, logical_w, logical_h)

        self.overlay.show()
        self.overlay.show_export_menu(QCursor.pos())

    def start_capture(self):
        if hasattr(self, 'overlay') and self.overlay:
            try:
                if self.overlay.isVisible():
                    return
            except RuntimeError:
                self.overlay = None

        screen = QApplication.screenAt(QCursor.pos())
        if not screen:
            screen = self.app.primaryScreen()
            
        full_screenshot = screen.grabWindow(0)
        self.overlay = CaptureOverlay(full_screenshot, tray_icon=self.tray_icon)
        self.overlay.show()

    def run(self):
        self.app.exec()

if __name__ == "__main__":
    app = ScreenshotApp()
    app.run()
